### ISSUE TITLE
`404` on https://service.unece.org/trade/uncefact/vocabulary/uncefact/

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#108]
https://service.unece.org/trade/uncefact/vocabulary/uncefact/ is not responding right now. 

@kevinbish, is anything going on on the UN servers?

**Comment by kevinbish** [comment]
Hi Nis, it should be online now. 
(Some updates from the CCL RDM's were running from the Gefeg to UNECE Repo.).
