### ISSUE TITLE
https://service.unece.org/trade/uncefact/vocabulary/uncefact-context.jsonld CORS issues

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [uncefact/spec-jsonld#114]
Due to CORS issues https://service.unece.org/trade/uncefact/vocabulary/uncefact-context.jsonld is not resolvable from the JSON-LD Playground 

Please could you check and fix it?

**Comment by nissimsan** [comment]
Good callout, @jmcanterafonseca-iota! 

@kevinbish, @kshychko. Assuming our deployment strategy works out as planned, is this a configuration to be made at UN side or on the host? I think the latter, but please keep me honest and share your thoughts...

**Comment by jmcanterafonseca-iota** [comment]
@nissimsan any progress on this?

**Comment by nissimsan** [comment]
We didn't get to discuss this on the call yesterday. @kshychko, do you mind if I tag you for your immediate thoughts on this?

**Comment by nissimsan** [comment]
This must be possible to configure cloudflare.

**Comment by nissimsan** [comment]
This issue will solve itself when v1 gets deployed.

**Comment by nissimsan** [comment]
Dependency on #119

**Comment by nissimsan** [comment]
Good stuff, @kshychko !

**Comment by nissimsan** [comment]
We did this.
