### ISSUE TITLE
unece DNS entry 

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#119]
NS record from 
`vocabulary.unece.org`
to 
`dmvc7xzscpizo.cloudfront.net`

@kevinbish, is this something you can run with, pls?

**Comment by nissimsan** [comment]
@kevinbish, can you kindly action this, pls?

**Comment by kevinbish** [comment]
@nissimsan Yes, I will submit the request.

**Comment by nissimsan** [comment]
This is in progress.

**Comment by nissimsan** [comment]
Current NS asked is `uncefact.org`.

**Comment by jmcanterafonseca-iota** [comment]
See #137

**Comment by nissimsan** [comment]
We did it!
