### ISSUE TITLE
Published URL path 

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#120]
We should change the current:
`https://service.unece.org/trade/uncefact/vocabulary/uncefact/#Accreditation`

To: 
`https://vocabulary.unece.org/Accreditation`,
`https://vocabulary.unece.org/Consignment`
etc... 

Attributes should be published alongside like this: 
`https://vocabulary.unece.org/billOfLadingNb`

And code lists like this: 
`https://vocabulary.unece.org/uncl1001`
with individual values distinguished by fragment: 
`https://vocabulary.unece.org/uncl1001#112`

**Comment by kshychko** [comment]
A draft version of published classes/properties from the BSP subset is available by the link below:
https://dmvc7xzscpizo.cloudfront.net/Accreditation

Code lists to be added.

**Comment by nissimsan** [comment]
This looks very promising!

**Comment by kshychko** [comment]
The Recommendation code lists have been added:
https://dmvc7xzscpizo.cloudfront.net/code-lists

**Comment by nissimsan** [comment]
Pending locodes and edifact code lists.

**Comment by nissimsan** [comment]
Requires front end work to avoid screen crashing.

**Comment by nissimsan** [comment]
Adding query parameter to navigate from country to locodes of that country

**Comment by kshychko** [comment]
The UN/LOCODEs column has been added to the UN/LOCODEs countries table:
https://dmvc7xzscpizo.cloudfront.net/unlocode-countries

**Comment by nissimsan** [comment]
This should be 
`https://dmvc7xzscpizo.cloudfront.net/unlocode#AFCBN`
not
`https://dmvc7xzscpizo.cloudfront.net/unlocodeaf#AFCBN`

**Comment by nissimsan** [comment]
Excellent job!
