### ISSUE TITLE
Add headline and UN logo on the html

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#123]
It should be clear where this is coming from: https://dmvc7xzscpizo.cloudfront.net/classes

Like this'ish: 
![image](https://user-images.githubusercontent.com/34443212/190357651-9e26e2c5-51d5-450d-a850-71679fd9acda.png)

**Comment by kshychko** [comment]
The logo has been added 
![image](https://user-images.githubusercontent.com/6890602/192975279-4b8efd61-5d7a-4c9d-9311-69d5d781fb82.png)

**Comment by nissimsan** [comment]
We did this.
