### ISSUE TITLE
Address the UN/LOCODE jsonld file size

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#130]
Currently it is 80 MB. We need to find a way to make it smaller or slice it up.

**Comment by nissimsan** [comment]
https://dmvc7xzscpizo.cloudfront.net/unlocode

**Comment by kshychko** [comment]
https://github.com/uncefact/codes-locode/blob/main/vocab/unlocode.jsonld

**Comment by nissimsan** [comment]
Thoughts/options discussed: 
1. Trim/minimization (@kshychko your action to give this a go)
2. Slice up by country (unfortunate usage consequences) 
3. Change file format

**Comment by kshychko** [comment]
UN/LOCODE vocabulary file has been minimized and its size is now less than 40Mb
https://github.com/uncefact/codes-locode/blob/main/vocab/unlocode.jsonld

**Comment by nissimsan** [comment]
Less than 40MB is good enough.
