### ISSUE TITLE
Change tab icon to UN logo

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#133]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/34443212/196176593-31c82b57-b345-4b54-86ff-37784050cba5.png">

This should be the real UN logo: 
<img width="47" alt="image" src="https://user-images.githubusercontent.com/34443212/196176850-a1c8c441-6e12-4b78-9a8e-6227ce93bf34.png">

**Comment by kshychko** [comment]
@nissimsan , fixed
