### ISSUE TITLE
Misalignment between Vocab and Context file on Website

### ISSUE THREAD

**Issue by ChrisJMacdonald** [uncefact/spec-jsonld#134]
On the draft [UNCEFACT JSON-LD vocabulary website](https://service.unece.org/trade/uncefact/vocabulary/uncefact/#sellerParty), there is a property `deliveryTermsDeliveryTypeCode`.

However, this does not show up in the [provided context file](https://service.unece.org/trade/uncefact/vocabulary/uncefact-context.jsonld), with `deliveryTypeDeliveryTermsCode` showing up instead.

I believe it's a simple case of the words being slightly switched around, but correct me if I'm wrong

Cheers

**Comment by jmcanterafonseca-iota** [comment]
is there a single source of truth ... in a huge Vocab like this any automated check could be fundamental
probably you need to get inspired by schema.org in how to handle big vocabularies

**Comment by nissimsan** [comment]
@ChrisJMacdonald, would you mind checking this again. Many bugs have been fixed since October, and I suspect this is probably resolved (other similar issues are). 

If the problem remains, please scream and shout about it so it gets attention. :)

Thanks!

**Comment by ChrisJMacdonald** [comment]
Can confirm that this one is fixed, Cheers!
