### ISSUE TITLE
Update unece @context file with term definitions from code lists

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#136]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/34443212/198234690-deee5be0-eb34-47c8-ade6-35c721089463.png">

These RDF classes are to be defined too: 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/34443212/198234828-52d933bb-77cd-40a6-98cc-3b910bc262ac.png">

**Comment by jmcanterafonseca-iota** [comment]
@nissimsan the code lists can be huge ... and the size of the LD Context can increase a lot ... 

could they be hosted in their own LD Context and then imported only if they are really used. In EPCIS we have only one LD Context that also contains the CBV Code Lists (enumerations in schema.org jargon) , but in EPCIS CBV code lists are not so long ... in any case we generate a single LD Context from multiple sources, see https://github.com/gs1/EPCIS/tree/master/JSON-LD-Context

**Comment by nissimsan** [comment]
@jmcanterafonseca-iota , are you suggesting that we combine the contexts into a single file? They are huge already. 

Context granularity is a trade off, there's no right and wrong. I sort of think that we've landed it in a pretty good middle ground with the two (pretty big) contexts.

**Comment by nissimsan** [comment]
We should probably just close this. What I am suggesting sounds like a bad idea.

**Comment by nissimsan** [comment]
We did this: https://vocabulary.uncefact.org/unlocode-vocab-context.jsonld
