### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by colugo** [uncefact/spec-jsonld#138]
I was attempting to load the full json-ld vocabulary (https://dmvc7xzscpizo.cloudfront.net/unece.jsonld) into Jargon.
This mostly worked, but Jargon complained there were a couple of classes missing.

They are:
- CoordinateReferenceSystem
- CustomsProcedure
- Preference

Looking at the rendered vocabulary site (https://dmvc7xzscpizo.cloudfront.net), these classes return 404, despite having links from other classes.

Eg: https://dmvc7xzscpizo.cloudfront.net/TelecommunicationCommunication has a link to Preference, which 404's

**Comment by nissimsan** [comment]
It would be great to remove broken links. 

I personally don't think this is `v1` worthy.

**Comment by nissimsan** [comment]
Is this still a thing? @colugo, a lot has happened since this - would you mind checking and confirm there is still a problem; or close the issue if we're good.

**Comment by nissimsan** [comment]
![image](https://user-images.githubusercontent.com/34443212/233294502-08d78f4d-8d60-48a5-8d60-18a0a6a9b34e.png)

Quick check, this seems fixed. Looks like we're good on this.

**Comment by colugo** [comment]
I think this is no longer an issue
