### ISSUE TITLE
New html vocab view is missing "referenced by" section for classes

### ISSUE THREAD

**Issue by Fak3** [uncefact/spec-jsonld#140]
Initial html vocab representation had very useful "referenced by" section for classes:

![Screenshot_20221110_130839](https://user-images.githubusercontent.com/991641/201063837-e5eace38-7973-49e3-8c7a-60c49326dc1b.jpg)

In the new design it is not implemented. Would be great to get it back, as it has very valuable info

**Comment by kshychko** [comment]
@Fak3, we do have `Referenced by` section:
![image](https://user-images.githubusercontent.com/6890602/203634256-9e9907b8-9eaa-4c63-9e94-016bcdcdc78d.png)

**Comment by Fak3** [comment]
I think it would be more clear to show this section even for the classes that are not referenced by any property, like https://vocabulary.uncefact.org/Context
`Referenced by: None`
