### ISSUE TITLE
LD Context: define convenient mappings for `@id` and `@type`

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [uncefact/spec-jsonld#144]
It would be good to define mappings in the LD Context as

```json
{
    "id": "@id",
   "type": "@type"
}
```

That way the adoption by JSON developers will be smoother

**Comment by nissimsan** [comment]
Agreed.

**Comment by kshychko** [comment]
There is a problem with UNECE context, because it already has https://vocabulary.uncefact.org/id and https://vocabulary.uncefact.org/type properties.
I assume we can rename them just in the context:

```
        "idProperty": {
            "@id": "unece:id",
            "@type": "xsd:token"
        },
        "typeProperty": {
            "@id": "unece:type",
            "@type": "xsd:string"
        }
```

@nissimsan , @jmcanterafonseca-iota , any thoughts?

**Comment by nissimsan** [comment]
Both these clash with existing attribute domain naming. 
Decision on the call: 
1. Change `id` back to `identifier`
2. Split the 7 `type`s into qualified types (e.g. `packingType`)
3. Add the two mappings as suggested on the description.

**Comment by kshychko** [comment]
Diff report:

```
Classes that exists in set1 but missing in set2 (were removed from set2) - 0:
Classes that exists in set2 but missing in set1 (were added to set2) - 0:
Properties that exists in set1 but missing in set2 (were removed from set2) - 2:
unece:id
unece:type
Properties that exists in set2 but missing in set1 (were added to set2) - 7:
unece:identifier
unece:packagingType
unece:priceType
unece:routeType
unece:taxType
unece:transportMeansType
unece:transportMovementType
```

**Comment by nissimsan** [comment]
We did this. We can close this.

**Comment by nissimsan** [comment]
We did it - closing
