### ISSUE TITLE
LDContext: The `@type` is missing in all properties where it is relevant

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [uncefact/spec-jsonld#146]
`@type` could be `id` for what you call object properties, 

it could be `@vocab` for what you call code lists, 

it could be `xsd:DateTime` (or timestamp), etc.

**Comment by nissimsan** [comment]
@jmcanterafonseca-iota , thank you so much for the excellent requirements you've raised!!

**Comment by nissimsan** [comment]
@jmcanterafonseca-iota , please confirm the new output and close ticket if done.

**Comment by nissimsan** [comment]
We did it - closing
