### ISSUE TITLE
Version label `19B` rather than `v1`

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#147]
Our focus on "v1" is quite technical, reflecting that the transform NDRs are implemented. But really, the relevant version to highlight is that of the source model, which I believe is `19B`. 
I propose we change from the current marking of v1 instead to 19B.

**Comment by kshychko** [comment]
@nissimsan, the [spreadsheet](https://github.com/uncefact/spec-jsonld/blob/main/scripts/transformer/src/main/resources/BSP%20D20A%20Context%20CCL.xlsx) with BSP subset that we are using as the data source is called `BSP D20A Context CCL` so probably it should be 20A.

**Comment by nissimsan** [comment]
The file name seems pretty evident. Let's go with 20A labelling.

**Comment by winnington** [comment]
@nissimsan @kshychko thanks, Draft D20A will be perfect labelling as the original D20A BSP XLS export was incomplete but was contributed for project development
