### ISSUE TITLE
"About" page content

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#149]
The current About page is quite nerdy. 

https://www.gs1.org/voc/ has slightly more business friendly approach which I find more appropriate. 

Search fits in well too.

**Comment by kshychko** [comment]
@nissimsan, could you please update the content of the about page with the more appropriate content
https://github.com/uncefact/vocabulary-outputs/blob/main/pages/about.html

**Comment by kshychko** [comment]
@nissimsan , preview is available for your PR  http://uncefact-preview.s3-website-us-east-1.amazonaws.com/about
