### ISSUE TITLE
Potential data source 

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#166]
This might be a better alternative source model:
https://github.com/uncefact/spec-JSONschema/tree/main/JSONschema2020-12/snapshot

Still seems to be 2020 (same as existing). And the structure will definitely need some consideration.

**Comment by AndreasPvd** [comment]
JSONschema2020-12 is used in this path, which is the very latest version of JSON **schema**. This is used to model the latest version of each of the three existing CCTS models: D17A for agriculture, D19B for accounting and D22A for Buy-ship-pay. But please use https://github.com/uncefact/spec-JSONschema/tree/main/JSONschema2020-12/library and not the snapshot-version, as the snapshot version only uses messsage-based information. 

As JSONschema 2020-12 is the latest version of the JSON schema standard, not all tools are supporting this  today. For this reason a second export in https://github.com/uncefact/spec-JSONschema/tree/main/compatability exists - again with a library and a snapshot variant. 

By the end of this week there will be a third export available designated especially for the JSON-LD vocab. It is based on JSON schema 2020-12 as well, but adds meta-information for e.g. for UN-ID and Business-Process.

**Comment by onthebreeze** [comment]
Thank you @AndreasPvd - but could you please explain how to extract ONLY the underlying BSP library (essentially the same thing that was last published as xls in version 19B) without any of the message based contextualisations?

All I can see in those links is a list of messages.

**Comment by nissimsan** [comment]
Here's the link to the most recent BSP source model: 

https://github.com/uncefact/spec-JSONschema/blob/main/JSONschema2020-12/meta-library/BuyShipPay/D22A/UNECE-BSPContextCCL.json

@AndreasPvd, FYI ^

**Comment by nissimsan** [comment]
Some thoughts on implementing this: 
1. Let's branch off the Transformer class for this new JSON Schema input format. 
2. We need to thoroughly review the output, so raise a PR on https://github.com/uncefact/vocabulary-outputs and let us spend the time to carefully review the changes before merging. It should only contain the actual source model modification done between v20A and v22A. Anything changes beyond that is a bug (either on our current output or on the new code). 

@kshychko, fyi ^

**Comment by nissimsan** [comment]
Great, @kshychko! Please keep iterating until the diff is down to recognisable set of classes.

**Comment by nissimsan** [comment]
We did this. Pending close.
