### ISSUE TITLE
subordinateSubordinateSubordinateLocation property name

### ISSUE THREAD

**Issue by kshychko** [uncefact/spec-jsonld#167]
Within the latest run of NDR rules after applying the fix for #139 we've got the following property:
https://vocabulary.uncefact.org/subordinateSubordinateSubordinateLocation

The full diff is available in #159 

Should we do something about it?

**Comment by nissimsan** [comment]
LOL - this is hilarious! Somehow very UN/CEFACT!  :D 

As bad as it looks, I am very(!) hesitant to make ndr changes to address specific situations like this. It looks more like an upstream oddity. Tagging as "semantic".

**Comment by nissimsan** [comment]
Reporting this upstream. CLosing issue
