### ISSUE TITLE
is there a bug in generation? or publishing?

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/spec-jsonld#174]
AccountingAccount class shows properties with no descriptions

![AccountingAccount](https://user-images.githubusercontent.com/13426392/228397291-4c1db8bf-4612-44f8-b042-9b0eda46ee3e.png)

But when clicking on the property, there does seem to be a description.

![payableSpecifiedAccountingAccount](https://user-images.githubusercontent.com/13426392/228397408-4b7a81d6-54bf-4fd4-a4d3-3d4582ac246d.png)

**Comment by kshychko** [comment]
That's a bug in publishing, in "Referenced by" cases, when a property has multiple comments (coming from property existing in different classes), aren't handled properly. I'll fix that.
