### ISSUE TITLE
publish as individual resources

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#26]
Currently you publish most UNECE vocabs as one big page.

- providing useful data for **individual** resources (called "entity RDF") is one of the basic tenets of the web architecture and Linked Data. It'd make semantic web crawlers unhappy to get megabytes of data when they want to use one of your entities
- having individual pages makes it easier and a lot more valuable for other knowledge graphs to link to your data. Eg consider:
  - https://www.wikidata.org/wiki/Property:P6512 (UNECE Rec20 code) has no formatter URL (because #24?)
  - https://www.wikidata.org/wiki/Property:P1937 (UN LOCODE) uses formatter URL `https://locode.info/$1` because these guys have individual pages (eg https://locode.info/CHGVA).
    - UNECE had them at some point but now `https://unece.org/fileadmin/DAM/cefact/locode/id/$1` is deprecated on WD

Or maybe publish both:
- small pages & RDF files for each individual resource
- a big page for the vocab URL, assembled from the small pages

**Comment by VladimirAlexiev** [comment]
The page https://service.unece.org/trade/uncefact/vocabulary/uncefact/ is too large, and wreaks havoc on my Chrome (page and browser become too sluggish). Laptop with 8Gb RAM.

**Comment by nissimsan** [comment]
@kshychko, please take a look, what options do we have.

**Comment by nissimsan** [comment]
Discussing this on the call. There's general agreement that splitting into individual pages would be much preferred. We're primarily debating the priority of this (we're a quite limited team).

**Comment by nissimsan** [comment]
@VladimirAlexiev , how should we do this exactly? Should we slice it into each resource having its own file? It'll be many thousands of files. Is that a better practice? (It will be a challenge for our brittle deployment process)

**Comment by Fak3** [comment]
> providing useful data for individual resources (called "entity RDF") is one of the basic tenets of the web architecture and Linked Data. It'd make semantic web crawlers unhappy to get megabytes of data when they want to use one of your entities

Can you please expand this "semantic web crawlers" usecase? I can hardly imagine that some web agent is only interested in single term from our vocab, but quite the opposite - to make sense of any term you have to download them all. So possibility to download the whole vocab seems more optimal.

Speaking of human convenience though, current html page is huge, loads slow and its hard for a human to grasp the concepts introduced in the vocabualry, because if its huge size. It would be nice if we could split html into page-per domain of knowledge. We discussed it briefly back then: https://github.com/edi3/edi3-json-ld-ndr/issues/13 but without any results.

**Comment by nissimsan** [comment]
Decision on Sept 1st 2022 on the call: 
- Make classes as individual pages (like https://ref.gs1.org/epcis/EPCISDocument) 
- Make code lists (like https://ref.gs1.org/cbv/BizStep, except use anchors (`#`) rather than)

**Comment by nissimsan** [comment]
Let's try LOCODES on a single page, see how it works - if we need to treat them somehow special, we'll make that decision later.

**Comment by nissimsan** [comment]
@kshychko, it'd be great to see [this](https://github.com/uncefact/spec-jsonld/issues/26#issuecomment-1233950290) on next meeting (Sept 15)

**Comment by nissimsan** [comment]
Work in progress: 
https://dmvc7xzscpizo.cloudfront.net/classes

**Comment by nissimsan** [comment]
We did this.
