### ISSUE TITLE
cefact namespace

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#35]
https://gist.github.com/VladimirAlexiev/618a9bddd6a949b75b37e983f0220417#bies

The `cefact:` namespace should be at `unece` rather than `edi3`, like the `uncefact:` namespace
```ttl
@prefix uncefact: <https://service.unece.org/trade/uncefact/trade/uncefact/vocabulary/uncefact#> .
@prefix cefact:   <https://edi3.org/cefact#> .
```
- The `cefact:` namespace doesn't reflect its purpose. Maybe it should be `uncefactBIE:`? And a corresponding part in the URL: `<uncefact/BIE/uncefact>`

**Comment by nissimsan** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/34443212/170664696-edc4d321-356d-4aba-b161-981b2580fa4a.png">
Definitely a bug

**Comment by kshychko** [comment]
`cefact` namespace value has been changed to `https://service.unece.org/trade/uncefact/vocabulary/cefact`:
https://github.com/uncefact/spec-jsonld/pull/112/files#diff-a12ec93e6434bcadf7fc3eaebf7fa191735c527dc75679f7beef58b011e56cfbR73

We still are going to separate it from `unece` namespace as data in `unece:cefactElementMetadata` element is for information and ids from there are not being published as RDF resources (at least for now).

**Comment by nissimsan** [comment]
Done: https://github.com/uncefact/spec-jsonld/pull/112
