### ISSUE TITLE
cefactBieDomainClass should be object prop not string

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#36]
The link from `BasicBIE` to `AggregateBIE` should be an object prop, not a string:
```
cefact:WorkItem_QuantityAnalysis.Details
        rdf:type                        uncefact:AggregateBIE .
cefact:WorkItem_QuantityAnalysis.Identification.Identifier
        rdf:type                        uncefact:BasicBIE ;
        uncefact:cefactBieDomainClass   "cefact:WorkItem_QuantityAnalysis.Details" # -> cefact:WorkItem_QuantityAnalysis.Details
```

**Comment by nissimsan** [comment]
Related to #63

**Comment by nissimsan** [comment]
![image](https://user-images.githubusercontent.com/34443212/175261794-597d0d76-bbc5-4bb2-b27a-97f5102834ff.png)

**Comment by Fak3** [comment]
>  Related to #63

It is not related to #63. This issue is about metadata "hints" for humans we leave to keep the trace from which BIE  the rdf class or property was generated.
To resolve this issue we should add proper type to our context:
 ```
 "@context": {
    ...
    "unece:cefactBieDomainClass": {
      "@type": "@id"
    }
  }
```

**Comment by nissimsan** [comment]
@kshychko fixed this
