### ISSUE TITLE
void values of uncefact:TDED

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#38]
some `uncefact:TDED "."` are void (empty) values: skip them.

And what is TDED? use words not abbreviations

**Comment by nissimsan** [comment]
TDED = Trade Data Element Directory. 

... Do we even need TDED in the vocab at all? I don't think we do.

**Comment by nissimsan** [comment]
@kshychko , please elaborate where this comes from.

**Comment by cmsdroff** [comment]
Here is the official definition https://unece.org/trade-facilitation-0

> **UNECE Trade Data Elements Directory (TDED)**
> The standard data elements included in the Directory are intended to facilitate interchange of data in international trade. These standard data elements can be used with any method of data interchange, on paper documents as well as with other means of data communication; they can be selected for transmission one by one, or used within a particular system of interchange rules, e.g. the United Nations syntax rules for Electronic Data Interchange For Administration, Commerce and Transport (UN/EDIFACT) developed within the UNECE and published as International Standard ISO 9735. Sections 1, 2, 3, 4 and 9 of the Directory constitute International Standard ISO 7372.
> 
> The UNTDED is updated, based on reviews by the Maintenance Agency, a joint UNECE - ISO body authorized by UN/CEFACT and by the ISO Council, entrusted with its maintenance in order to keep the UNTDED/ISO7372 up to date to meet changes and new requirements in trade.
> 
> Website: http://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/standards/untded-iso7372/introducing-untded-iso7372.html

**Comment by onthebreeze** [comment]
TDED - means "Trade Data Element Directory" - it's the vocabulary that supported the old EDIFACT domain.  Not sure how it got into this JSON-LD vocabulary but maybe from EDIFACT code lists which we pulled into this vocabulary but arent in the Core component library?  

@kshychko - could you figure out where this came from?  then we can answer the question about what to do with it

**Comment by VladimirAlexiev** [comment]
It's some code on BIEs:
```ttl
cefact:Exchanged_Document.Acceptance.DateTime uncefact:TDED "2097"
```

I vote to keep it but rename to lowercase, omit the void values ".", and define it properly:
```ttl
uncefact:tded a owl:DatatypeProperty;
  rdfs:label "TDED";
  schema:domainIncludes TODO;
  schema:rangeIncludes xsd:string;
  rdfs:comment "Trade Data Elements Directory code";
  skos:scopeNote "4-digit code of the BIE";
  rdfs:seeAlso <http://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-business-uncefact/outputs/standards/untded-iso7372/introducing-untded-iso7372.html>.
```

**Comment by nissimsan** [comment]
Agreement on the call to skip the blanks. We don't have to explicitly capture "there is no TDED mapping for this value".

**Comment by nissimsan** [comment]
@kshychko , please confirm that this is fixed already?

**Comment by kshychko** [comment]
`TDED` property has been renamed to `tded` and empty ('.') values are ignored.

**Comment by kshychko** [comment]
As the next step, we can publish EDIFACT codes and link to them the properties with TDED defined.

**Comment by nissimsan** [comment]
Done: https://github.com/uncefact/spec-jsonld/pull/112

**Comment by VladimirAlexiev** [comment]
* The decision to skip empty values is recorded in https://github.com/uncefact/spec-jsonld/blob/main/meeting-minutes/23-06-2022.md#tickets
* However, the problem has reappeared. Eg here's a BIE to illustrate it (converted to Turtle):
```ttl
cefact:Academic_Qualification.AbbreviatedName.Text
        rdf:type                        uncefact:BasicBIE ;
        rdfs:comment                    "The abbreviated name, expressed as text, of this academic qualification." ;
        uncefact:TDED                   "." ;
        uncefact:cefactBieDomainClass   "cefact:Academic_Qualification.Details" ;
        uncefact:cefactBusinessProcess  "In All Contexts" ;
        uncefact:cefactUNId             "cefact:UN01002518" .
```
