### ISSUE TITLE
uncefact:UNECELOCODE

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#39]
uncefact.jsonld wrongly defines class `uncefact:UNECELOCODE`
- The LOCODE instance data uses `uncefact:UNLOCODE` rather than this name
- Furthermore, this class is not very meaningful semantically (see https://github.com/uncefact/vocab/issues/29), which may be confirmed by its "description" below:
```ttl
uncefact:UNECELOCODE  rdf:type  rdfs:Class ;
        rdfs:comment  "LOCODE." ;
        rdfs:label    "UNLOCODE" .
```

**Comment by nissimsan** [comment]
@kshychko , `uncefact:UNECELOCODE` seems like a bug?

**Comment by nissimsan** [comment]
Related to #27

**Comment by kshychko** [comment]
https://github.com/uncefact/codes-locode/blob/main/vocab/unlocode/UNLOCODE.jsonld

**Comment by nissimsan** [comment]
Will be tackled in https://github.com/uncefact/spec-jsonld/pull/105 also.

**Comment by nissimsan** [comment]
We did this: https://github.com/uncefact/spec-jsonld/pull/105
