### ISSUE TITLE
owl:ObjectProperty vs owl:DatatypeProperty, rather than rdf:Property

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#40]
https://gist.github.com/VladimirAlexiev/618a9bddd6a949b75b37e983f0220417#props

schema.org uses `rdf:Property` because almost all of its props allow literal (text) in addition to object. 
However, UNCEFACT seems to be strict in following a "property dichotomy", so use owl:ObjectProperty (797, see below) vs owl:DatatypeProperty (950).

| range      |   c | comment                         |
|------------|-----|---------------------------------|
| xsd:string | 791 | all literals                    |
| xsd:token  | 159 | identifiers, all end in `Id`    |
| uncefact:  | 797 | uncefact classes (object props) |

**Comment by nissimsan** [comment]
@Fak3

**Comment by Fak3** [comment]
Yes, it makes sense, so we can use those more specific properties. 

But as a side note, maybe one day we would want to introduce such flexible Datatype-or-Relation properties? We can keep in mind that as an option and collect pros\cons of doing so.

**Comment by VladimirAlexiev** [comment]
#55 asks to promote some data props (IDs) to object props (URLs)

**Comment by nissimsan** [comment]
@Fak3 , would you mind taking a closer look at this, pls?

**Comment by nissimsan** [comment]
@VladimirAlexiev , it's confusing what you mean "owl:ObjectProperty (797, see below) vs owl:DatatypeProperty (950)" - which one should replace `rdf:Property`?

**Comment by nissimsan** [comment]
We did this.
