### ISSUE TITLE
"Code" props: change to xsd:token, vs rename 

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#47]
Props named `xxxCode` come in two kinds:
```sparql
prefix uncefact: <https://service.unece.org/trade/uncefact/trade/uncefact/vocabulary/uncefact#> 
PREFIX schema: <http://schema.org/>
select ?range (count(*) as ?c) {
  ?prop schema:rangeIncludes ?range1
  filter(regex(str(?prop),"Code$"))
  bind(if(strstarts(str(?range1),str(uncefact:)),uncefact:,?range1) as ?range)
} group by ?range
```

- `xsd:string`: 154. Consider mapping to range `xsd:token` (same as props named `xxxId`).
  xsd:oken doesn't allow leading, consecutive and trailing spaces, so it fits better than xsd:string. Example:
  - `accessRightsCode xsd:string` -> `xsd:token`
- `uncefct:...` (objects, i.e. codelist values): 110. Consider renaming them to remove `Code` (because objects are not codes!). Examples:
  - `accountingDocumentSetTriggerCode uncefact:UNCL1001Code` -> `accountingDocumentSetTrigger`
  - `cross-BorderRegulatoryProcedureTypeCode uncefact:UNCL9353Code` ->  `cross-BorderRegulatoryProcedureType`
  - `logisticsSealSealingPartyRoleCode uncefact:UNCL9303Code` -> `logisticsSealSealingPartyRole`

**Comment by nissimsan** [comment]
Good suggestion making these `xsd:token`. @kshychko , tagging you to make this change. 

Discussion it on the call, we reject the suggestion of removing "Code", though.

**Comment by nissimsan** [comment]
Not sure what kept us from closing this earlier. Seems like a mistake.
