### ISSUE TITLE
Repo name? 

### ISSUE THREAD

**Issue by nissimsan** [uncefact/spec-jsonld#98]
With the github.com/uncefact/ shaping up, we should align to a larger naming convention. Something `spec-xxx`. Any suggestions on a better name? `/vocab` was starting to feel weak anyway.

**Comment by onthebreeze** [comment]
can we please agree to a repo name called

spec-jsonld 

I'd like to change it so that I can correctly reference it from other documents - notably the whitepaper on VCs for cross borer trade.
